In [195]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.python.keras import layers
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score, accuracy_score

In [196]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [197]:
data = pd.read_csv("/content/drive/MyDrive/Copy of Train.csv")
data

,Team1,Team2,Stadium,HostCountry,Team1_Venue,Team2_Venue,Team1_Innings,Team2_Innings,MonthOfMatch,MatchWinner
0,5,4,37,4,Home,Away,Second,First,Dec,4
1,1,14,84,7,Neutral,Neutral,First,Second,Sep,1
2,9,15,47,9,Home,Away,First,Second,Feb,9
3,7,2,102,6,Home,Away,First,Second,Aug,2
4,6,8,46,5,Home,Away,First,Second,Aug,6
...,...,...,...,...,...,...,...,...,...,...
2503,5,15,89,3,Neutral,Neutral,Second,First,Jun,5
2504,1,14,138,0,Home,Away,First,Second,Jan,1
2505,14,5,135,15,Home,Away,Second,First,Apr,14
2506,15,14,64,16,Home,Away,First,Second,Nov,14
2507,1,10,111,0,Home,Away,Second,First,Jan,1

In [198]:
data.isna().sum()

Team1            0
Team2            0
Stadium          0
HostCountry      0
Team1_Venue      0
Team2_Venue      0
Team1_Innings    0
Team2_Innings    0
MonthOfMatch     0
MatchWinner      0
dtype: int64

In [199]:
data['MatchWinner'].value_counts()

MatchWinner
1     379
5     318
10    316
14    262
13    246
12    245
4     237
9     223
15     87
2      70
6      33
0      27
7      24
11     18
8      15
3       8
Name: count, dtype: int64

In [200]:
categories = ['Team1', 'Team2', 'Stadium', 'HostCountry', 'Team1_Venue', 'Team2_Venue', 'Team1_Innings', 'Team2_Innings', 'MonthOfMatch']
X = data[categories]
y = data[['MatchWinner']]

In [201]:
encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(X[['Team1', 'Team2', 'Stadium', 'HostCountry', 'Team1_Venue', 'Team2_Venue', 'Team1_Innings', 'Team2_Innings', 'MonthOfMatch']])

In [202]:
X_transformed = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(['Team1', 'Team2', 'Stadium', 'HostCountry', 'Team1_Venue', 'Team2_Venue', 'Team1_Innings', 'Team2_Innings', 'MonthOfMatch']))
X_transformed

,Team1_0,Team1_1,Team1_2,Team1_3,Team1_4,Team1_5,Team1_6,Team1_7,Team1_8,Team1_9,...,MonthOfMatch_Dec,MonthOfMatch_Feb,MonthOfMatch_Jan,MonthOfMatch_Jul,MonthOfMatch_Jun,MonthOfMatch_Mar,MonthOfMatch_May,MonthOfMatch_Nov,MonthOfMatch_Oct,MonthOfMatch_Sep
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2503,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2504,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2505,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2506,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2507,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [203]:
X_train = X_transformed[:2108]
y_train = y[:2108]
X_test = X_transformed[2108:]
y_test = y[2108:]

In [216]:
model = tf.keras.Sequential([
    layers.Flatten(input_shape=(2108, 218)),
    layers.Dense(700, activation="relu"),
    layers.Dense(350, activation="relu"),
    layers.Dense(16, activation="softmax")
])

In [217]:
model.compile(optimizer="adam", loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics = ['accuracy'])

In [218]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
66/66 [==============================] - 1s 8ms/step - loss: 1.6019 - accuracy: 0.5090
Epoch 2/10
66/66 [==============================] - 1s 12ms/step - loss: 0.8086 - accuracy: 0.6613
Epoch 3/10
66/66 [==============================] - 1s 12ms/step - loss: 0.6570 - accuracy: 0.7130
Epoch 4/10
66/66 [==============================] - 1s 12ms/step - loss: 0.5699 - accuracy: 0.7462
Epoch 5/10
66/66 [==============================] - 1s 12ms/step - loss: 0.4994 - accuracy: 0.7770
Epoch 6/10
66/66 [==============================] - 1s 12ms/step - loss: 0.4537 - accuracy: 0.7917
Epoch 7/10
66/66 [==============================] - 1s 12ms/step - loss: 0.4174 - accuracy: 0.8055
Epoch 8/10
66/66 [==============================] - 1s 12ms/step - loss: 0.4002 - accuracy: 0.8197
Epoch 9/10
66/66 [==============================] - 1s 11ms/step - loss: 0.3653 - accuracy: 0.8302
Epoch 10/10
66/66 [==============================] - 1s 8ms/step - loss: 0.3679 - accuracy: 0.8354

In [219]:
probs = model.predict(X_test)
y_pred = np.argmax(probs, axis=1)
y_pred

13/13 [==============================] - 0s 3ms/step

array([14,  4, 12,  0, 13, 14,  5,  1,  1, 13, 13,  1,  0, 13,  1, 15, 13,
        5, 12, 13,  5, 10,  4,  9, 14,  5, 13,  4,  5,  1, 15,  6, 10, 14,
       13,  1, 14,  1,  5,  4,  1,  1, 10, 10,  0, 10,  1, 14,  1,  1, 14,
        5,  5,  5, 12, 13, 14,  0,  5,  5,  5,  9,  5,  4, 12, 14,  4, 10,
        4,  5,  9,  5, 14,  1,  2, 10,  8, 12, 12, 13,  5, 12, 13,  4,  4,
        5,  7,  1, 14,  5,  0,  2, 13, 10, 10, 12,  9, 14, 13,  5,  9,  1,
        1, 10, 10, 12,  9,  4,  5,  5,  7, 14, 15,  1, 10,  1,  4,  9, 14,
       10, 12,  9,  9,  1,  9, 15, 13,  5, 12,  5,  5,  1, 10,  1,  5, 14,
        5,  1,  1, 13, 10,  1, 14, 13, 10, 14,  9,  1, 15,  5, 15, 13, 10,
       11,  1, 10, 12,  9,  2,  0,  5, 14,  1, 15, 13, 13, 13, 13,  1,  1,
       10,  4,  4, 10,  1, 11,  1,  5, 15, 15, 13, 12, 13,  1,  5,  5,  5,
       10, 10,  4, 12,  9, 13,  5, 14, 10, 15, 10, 10,  7,  1,  5,  9,  4,
        1,  1,  1,  5,  2,  1,  1,  1, 10,  4, 14, 13,  5, 14, 13, 10,  4,
        1, 12,  4,  4, 14, 10, 12, 13,  9,  1,  1,  5,  1,  1,  2,  4, 10,
        4, 13,  9,  5,  1,  4, 13,  4,  5, 14,  5,  1,  9,  5, 10, 13, 14,
        5,  4,  1,  2, 15,  5, 14,  2,  9,  6,  1, 12, 12,  4,  5, 10, 14,
        2, 15, 14, 12,  0, 10,  1,  5,  5,  5, 12, 14,  6,  2, 10, 12,  5,
       14,  6,  5, 13,  1,  9, 12, 14,  5,  5,  4, 13, 10, 12,  4,  5,  5,
       12, 12,  5,  2,  9, 12,  9, 10, 10,  2,  1,  1, 14, 10,  4,  6, 10,
       10,  9,  5,  1,  0, 14, 10,  4, 10,  9,  5,  9,  1, 12,  5,  6,  5,
        1,  9,  2, 14,  9,  1, 12,  1, 14, 10,  5, 12,  1,  5,  4, 13, 15,
       10, 10, 12,  4, 14,  1,  9,  1, 14,  2, 13,  5, 13,  9,  4,  9, 14,
        9, 12, 10, 12, 14, 13,  5, 13, 15,  9,  2, 12,  1,  5, 12,  1,  9,
       12, 13,  1,  1,  5,  1, 14, 14,  1])

In [220]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(test_acc)

13/13 [==============================] - 0s 3ms/step - loss: 1.0437 - accuracy: 0.6000
0.6000000238418579

In [221]:
accuracy_score(y_test, y_pred)

0.6