In [148]:
import numpy as np
import pandas as pd

In [149]:
df = pd.read_csv("Train.csv")

In [150]:
df.head()

,Team1,Team2,Stadium,HostCountry,Team1_Venue,Team2_Venue,Team1_Innings,Team2_Innings,MonthOfMatch,MatchWinner
0,5,4,37,4,Home,Away,Second,First,Dec,4
1,1,14,84,7,Neutral,Neutral,First,Second,Sep,1
2,9,15,47,9,Home,Away,First,Second,Feb,9
3,7,2,102,6,Home,Away,First,Second,Aug,2
4,6,8,46,5,Home,Away,First,Second,Aug,6

In [151]:
df.isna().sum()

Team1            0
Team2            0
Stadium          0
HostCountry      0
Team1_Venue      0
Team2_Venue      0
Team1_Innings    0
Team2_Innings    0
MonthOfMatch     0
MatchWinner      0
dtype: int64

In [152]:
# c=one hot encoding
df_encoded = pd.get_dummies(df["Team1"],prefix="Team1")
df = pd.concat([df, df_encoded], axis=1)
df.drop(["Team1"], axis=1, inplace=True)
df_encoded = pd.get_dummies(df["Team2"],prefix="Team2")
df = pd.concat([df, df_encoded], axis=1)
df.drop(["Team2"], axis=1, inplace=True)
df.head()

,Stadium,HostCountry,Team1_Venue,Team2_Venue,Team1_Innings,Team2_Innings,MonthOfMatch,MatchWinner,Team1_0,Team1_1,...,Team2_6,Team2_7,Team2_8,Team2_9,Team2_10,Team2_11,Team2_12,Team2_13,Team2_14,Team2_15
0,37,4,Home,Away,Second,First,Dec,4,False,False,...,False,False,False,False,False,False,False,False,False,False
1,84,7,Neutral,Neutral,First,Second,Sep,1,False,True,...,False,False,False,False,False,False,False,False,True,False
2,47,9,Home,Away,First,Second,Feb,9,False,False,...,False,False,False,False,False,False,False,False,False,True
3,102,6,Home,Away,First,Second,Aug,2,False,False,...,False,False,False,False,False,False,False,False,False,False
4,46,5,Home,Away,First,Second,Aug,6,False,False,...,False,False,True,False,False,False,False,False,False,False

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2508 entries, 0 to 2507
Data columns (total 40 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Stadium        2508 non-null   int64
 1   HostCountry    2508 non-null   int64
 2   Team1_Venue    2508 non-null   object
 3   Team2_Venue    2508 non-null   object
 4   Team1_Innings  2508 non-null   object
 5   Team2_Innings  2508 non-null   object
 6   MonthOfMatch   2508 non-null   object
 7   MatchWinner    2508 non-null   int64
 8   Team1_0        2508 non-null   bool
 9   Team1_1        2508 non-null   bool
 10  Team1_2        2508 non-null   bool
 11  Team1_3        2508 non-null   bool
 12  Team1_4        2508 non-null   bool
 13  Team1_5        2508 non-null   bool
 14  Team1_6        2508 non-null   bool
 15  Team1_7        2508 non-null   bool
 16  Team1_8        2508 non-null   bool
 17  Team1_9        2508 non-null   bool
 18  Team1_10       2508 non-null   bool
 19  Team1_11       2508 non-null   bool
 20  Team1_12       2508 non-null   bool
 21  Team1_13       2508 non-null   bool
 22  Team1_14       2508 non-null   bool
 23  Team1_15       2508 non-null   bool
 24  Team2_0        2508 non-null   bool
 25  Team2_1        2508 non-null   bool
 26  Team2_2        2508 non-null   bool
 27  Team2_3        2508 non-null   bool
 28  Team2_4        2508 non-null   bool
 29  Team2_5        2508 non-null   bool
 30  Team2_6        2508 non-null   bool
 31  Team2_7        2508 non-null   bool
 32  Team2_8        2508 non-null   bool
 33  Team2_9        2508 non-null   bool
 34  Team2_10       2508 non-null   bool
 35  Team2_11       2508 non-null   bool
 36  Team2_12       2508 non-null   bool
 37  Team2_13       2508 non-null   bool
 38  Team2_14       2508 non-null   bool
 39  Team2_15       2508 non-null   bool
dtypes: bool(32), int64(3), object(5)
memory usage: 235.2+ KB

In [154]:
df.drop(["Stadium","MonthOfMatch","Team2_Innings"],axis=1,inplace=True) #dropped Innings of team2 because team1 innings are complementary, there is no new information, month of match and stadium affect wwinner negligibly

In [155]:
df["Team1_Innings"]=df["Team1_Innings"].apply(lambda x: x=="First")

In [156]:
df

,HostCountry,Team1_Venue,Team2_Venue,Team1_Innings,MatchWinner,Team1_0,Team1_1,Team1_2,Team1_3,Team1_4,...,Team2_6,Team2_7,Team2_8,Team2_9,Team2_10,Team2_11,Team2_12,Team2_13,Team2_14,Team2_15
0,4,Home,Away,False,4,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,7,Neutral,Neutral,True,1,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,9,Home,Away,True,9,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,6,Home,Away,True,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,5,Home,Away,True,6,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2503,3,Neutral,Neutral,False,5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2504,0,Home,Away,True,1,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2505,15,Home,Away,False,14,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2506,16,Home,Away,True,14,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2507,0,Home,Away,False,1,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [157]:
df["Team2_Venue"].value_counts()

Team2_Venue
Away       1797
Neutral     710
Home          1
Name: count, dtype: int64

In [158]:
df_encoded = pd.get_dummies(df["Team1_Venue"],prefix="Team1_Venue")
df = pd.concat([df, df_encoded], axis=1)
df.drop(["Team1_Venue"], axis=1, inplace=True)

df_encoded = pd.get_dummies(df["Team2_Venue"],prefix="Team2_Venue")
df = pd.concat([df, df_encoded], axis=1)
df.drop(["Team2_Venue"], axis=1, inplace=True)

df_encoded = pd.get_dummies(df["HostCountry"],prefix="HostCountry")
df = pd.concat([df, df_encoded], axis=1)
df.drop(["HostCountry"], axis=1, inplace=True)

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2508 entries, 0 to 2507
Data columns (total 57 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Team1_Innings        2508 non-null   bool
 1   MatchWinner          2508 non-null   int64
 2   Team1_0              2508 non-null   bool
 3   Team1_1              2508 non-null   bool
 4   Team1_2              2508 non-null   bool
 5   Team1_3              2508 non-null   bool
 6   Team1_4              2508 non-null   bool
 7   Team1_5              2508 non-null   bool
 8   Team1_6              2508 non-null   bool
 9   Team1_7              2508 non-null   bool
 10  Team1_8              2508 non-null   bool
 11  Team1_9              2508 non-null   bool
 12  Team1_10             2508 non-null   bool
 13  Team1_11             2508 non-null   bool
 14  Team1_12             2508 non-null   bool
 15  Team1_13             2508 non-null   bool
 16  Team1_14             2508 non-null   bool
 17  Team1_15             2508 non-null   bool
 18  Team2_0              2508 non-null   bool
 19  Team2_1              2508 non-null   bool
 20  Team2_2              2508 non-null   bool
 21  Team2_3              2508 non-null   bool
 22  Team2_4              2508 non-null   bool
 23  Team2_5              2508 non-null   bool
 24  Team2_6              2508 non-null   bool
 25  Team2_7              2508 non-null   bool
 26  Team2_8              2508 non-null   bool
 27  Team2_9              2508 non-null   bool
 28  Team2_10             2508 non-null   bool
 29  Team2_11             2508 non-null   bool
 30  Team2_12             2508 non-null   bool
 31  Team2_13             2508 non-null   bool
 32  Team2_14             2508 non-null   bool
 33  Team2_15             2508 non-null   bool
 34  Team1_Venue_Away     2508 non-null   bool
 35  Team1_Venue_Home     2508 non-null   bool
 36  Team1_Venue_Neutral  2508 non-null   bool
 37  Team2_Venue_Away     2508 non-null   bool
 38  Team2_Venue_Home     2508 non-null   bool
 39  Team2_Venue_Neutral  2508 non-null   bool
 40  HostCountry_0        2508 non-null   bool
 41  HostCountry_1        2508 non-null   bool
 42  HostCountry_2        2508 non-null   bool
 43  HostCountry_3        2508 non-null   bool
 44  HostCountry_4        2508 non-null   bool
 45  HostCountry_5        2508 non-null   bool
 46  HostCountry_6        2508 non-null   bool
 47  HostCountry_7        2508 non-null   bool
 48  HostCountry_8        2508 non-null   bool
 49  HostCountry_9        2508 non-null   bool
 50  HostCountry_10       2508 non-null   bool
 51  HostCountry_11       2508 non-null   bool
 52  HostCountry_12       2508 non-null   bool
 53  HostCountry_13       2508 non-null   bool
 54  HostCountry_14       2508 non-null   bool
 55  HostCountry_15       2508 non-null   bool
 56  HostCountry_16       2508 non-null   bool
dtypes: bool(56), int64(1)
memory usage: 156.9 KB

In [160]:
x = np.array(df.drop(["MatchWinner"],axis=1))
y = np.array(pd.get_dummies(df["MatchWinner"]))
x_test = x[-400:]
y_test = y[-400:]
x = x[:-400]
y = y[:-400]

In [161]:
x.shape

(2108, 56)

In [162]:
import tensorflow as tf
import keras
from keras import layers

model = keras.Sequential(
    [
        layers.Dense(57,activation='relu'),
        layers.Dense(200,activation='relu'),
        layers.Dense(200,activation='relu'),
        layers.Dense(16,activation='sigmoid'),
    ]
)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [163]:
model.fit(x,y,epochs=30)

Epoch 1/30
66/66 [==============================] - 1s 2ms/step - loss: 2.1067 - accuracy: 0.3828
Epoch 2/30
66/66 [==============================] - 0s 3ms/step - loss: 1.1135 - accuracy: 0.5987
Epoch 3/30
66/66 [==============================] - 0s 2ms/step - loss: 0.8383 - accuracy: 0.6300
Epoch 4/30
66/66 [==============================] - 0s 2ms/step - loss: 0.7618 - accuracy: 0.6352
Epoch 5/30
66/66 [==============================] - 0s 2ms/step - loss: 0.7096 - accuracy: 0.6708
Epoch 6/30
66/66 [==============================] - 0s 3ms/step - loss: 0.6958 - accuracy: 0.6632
Epoch 7/30
66/66 [==============================] - 0s 2ms/step - loss: 0.6768 - accuracy: 0.6651
Epoch 8/30
66/66 [==============================] - 0s 3ms/step - loss: 0.6466 - accuracy: 0.6779
Epoch 9/30
66/66 [==============================] - 0s 2ms/step - loss: 0.6184 - accuracy: 0.6988
Epoch 10/30
66/66 [==============================] - 0s 2ms/step - loss: 0.6440 - accuracy: 0.6746
Epoch 11/30
66/66 [==============================] - 0s 2ms/step - loss: 0.6138 - accuracy: 0.6931
Epoch 12/30
66/66 [==============================] - 0s 2ms/step - loss: 0.6161 - accuracy: 0.6812
Epoch 13/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5963 - accuracy: 0.6931
Epoch 14/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5884 - accuracy: 0.6931
Epoch 15/30
66/66 [==============================] - 0s 3ms/step - loss: 0.5756 - accuracy: 0.7064
Epoch 16/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5765 - accuracy: 0.6969
Epoch 17/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5866 - accuracy: 0.6983
Epoch 18/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5668 - accuracy: 0.7026
Epoch 19/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5675 - accuracy: 0.6988
Epoch 20/30
66/66 [==============================] - 0s 3ms/step - loss: 0.5503 - accuracy: 0.7054
Epoch 21/30
66/66 [==============================] - 0s 3ms/step - loss: 0.5546 - accuracy: 0.7016
Epoch 22/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5497 - accuracy: 0.6964
Epoch 23/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5589 - accuracy: 0.7102
Epoch 24/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5598 - accuracy: 0.7030
Epoch 25/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5466 - accuracy: 0.7158
Epoch 26/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5394 - accuracy: 0.7092
Epoch 27/30
66/66 [==============================] - 0s 3ms/step - loss: 0.5372 - accuracy: 0.7149
Epoch 28/30
66/66 [==============================] - 0s 3ms/step - loss: 0.5511 - accuracy: 0.7087
Epoch 29/30
66/66 [==============================] - 0s 3ms/step - loss: 0.5484 - accuracy: 0.7144
Epoch 30/30
66/66 [==============================] - 0s 2ms/step - loss: 0.5357 - accuracy: 0.7120

In [164]:
from sklearn.metrics import accuracy_score
accuracy_score(np.argmax(model.predict(x_test),axis=1),np.argmax(y_test,axis=1))

13/13 [==============================] - 0s 2ms/step

0.6125